//
//  BlurModelManager.swift
//  Snap Sweeper
//
//  Created by Carla Segura on 3/26/26.
//  Description: Takes a UIImage, prepares it for the model, and returns a blur score
//  (0.0 = sharp, 1.0 = blurry).

import SwiftUI
import CoreML
import UIKit

final class BlurModelManager {

    // function to get a blur score from an image
    func predictBlurScore(from image: UIImage) -> Double? {
        
        
        guard let resizedImage = image.resized(to: CGSize(width: 224, height: 224)),
              let multiArray = resizedImage.toMLMultiArray() else {
            return nil
        }
        
        do {
            let config = MLModelConfiguration()
            
            // Note:
            // Might move this outside the function since it currently loads every time this function runs
            let model = try BlurRegressorMobileNetV3(configuration: config)
            let prediction = try model.prediction(image: multiArray)
            
            // Note:
            //"var_765" is auto-generated by Xcode. Name might change if model is re-exported
            let output = prediction.var_765
            let score = output[0].doubleValue
            
            return score
            
        } catch {
            print("Prediction failed: \(error)")
            return nil
        }
    }
}




